In [4]:
import numpy as np

In [5]:
my_list1 = [5,6,7,8]

In [6]:
my_array1 = np.array(my_list1)

In [7]:
my_array1

array([5, 6, 7, 8])

In [8]:
my_list2 = [510,12,13,14]

In [10]:
my_lists=[my_list1,my_list2]

In [11]:
my_lists

[[5, 6, 7, 8], [510, 12, 13, 14]]

In [12]:
my_array2 = np.array(my_lists)

In [14]:
my_array2

array([[  5,   6,   7,   8],
       [510,  12,  13,  14]])

In [15]:
my_array2.shape

(2L, 4L)

In [16]:
my_array2.dtype

dtype('int32')

In [17]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [19]:
my_zeros_array = np.zeros(5)

In [20]:
my_zeros_array.dtype

dtype('float64')

In [21]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [22]:
np.ones([5,5,5])

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]]])

In [23]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [24]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [25]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [26]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])