In [1]:
import numpy as np

In [4]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [6]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [7]:
A = np.random.randn(10)
A

array([ 0.7823098 ,  0.13860419,  0.87800117,  1.242134  , -0.1445972 ,
        0.2267723 ,  0.1774514 ,  0.0425923 , -0.24455981, -1.33714031])

In [8]:
B = np.random.randn(10)
B

array([ 0.33996881, -0.09962995, -0.56103298, -0.50971105,  0.11239006,
       -0.87536283,  0.2207253 ,  1.5176252 , -0.07149486, -0.65801877])

In [9]:
# Binary Functions
np.add(A,B)

array([ 1.12227861,  0.03897424,  0.31696819,  0.73242295, -0.03220714,
       -0.64859053,  0.3981767 ,  1.5602175 , -0.31605467, -1.99515908])

In [10]:
np.maximum(A,B)

array([ 0.7823098 ,  0.13860419,  0.87800117,  1.242134  ,  0.11239006,
        0.2267723 ,  0.2207253 ,  1.5176252 , -0.07149486, -0.65801877])

In [11]:
#For full and extensive list of all universal functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True