In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [8]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
ser1 = Series([0,1,2], index=['T','U','V'])

In [10]:
ser2 = Series([3,4],index=['X','Y'])


In [11]:
ser1

T    0
U    1
V    2
dtype: int64

In [12]:
ser2

X    3
Y    4
dtype: int64

In [13]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [16]:
pd.concat([ser1,ser2],axis=1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [17]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [18]:
dframe1=DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2=DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])
dframe1

X         Y         Z
0 -0.505260  1.618344 -0.112487
1 -1.355735  0.351875  0.602972
2 -1.359261  2.247949 -0.203834
3 -0.395182  0.393481  0.016197

In [19]:
dframe2

Y         Q         X
0  0.909821  0.953883  0.530844
1 -0.817866  1.255493 -0.512678
2  0.470648  1.852030 -0.464006

In [20]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -0.505260  1.618344 -0.112487
1       NaN -1.355735  0.351875  0.602972
2       NaN -1.359261  2.247949 -0.203834
3       NaN -0.395182  0.393481  0.016197
0  0.953883  0.530844  0.909821       NaN
1  1.255493 -0.512678 -0.817866       NaN
2  1.852030 -0.464006  0.470648       NaN

In [21]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN -0.505260  1.618344 -0.112487
1       NaN -1.355735  0.351875  0.602972
2       NaN -1.359261  2.247949 -0.203834
3       NaN -0.395182  0.393481  0.016197
4  0.953883  0.530844  0.909821       NaN
5  1.255493 -0.512678 -0.817866       NaN
6  1.852030 -0.464006  0.470648       NaN

In [ ]:
url='http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html'